server:
  port: 8086

spring:
  application:
    name: profile

keycloak:
  realm.name: ${KEYCLOAK_REALM_NAME:E-GROCERY} 
  server-url: ${KEYCLOAK_SERVER_URL:}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

      group.readiness.include: '*'
      group.readiness.show-details: always

      group.liveness.include: '*'
      group.liveness.show-details: always

  endpoints:
    web:
      exposure:
        include: '*'
