server:
  port: 8081

spring:
  application:
    name: product
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: false
      format_sql: false
      jdbc.time_zone: UTC
  liquibase:
    enabled: true
    contexts: dev
  datasource:
    url: ${POSTGRESS_URL:jdbc:postgresql://postgres.default.svc.cluster.local:5432/product}
    username: ${POSTGRES_USER:postgress}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    name: main

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

      group.readiness.include: '*'
      group.readiness.show-details: always

      group.liveness.include: '*'
      group.liveness.show-details: always

  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
