server:
  port: 8088
#this is new line added
spring:
  application:
    name: notification
  liquibase:
    enabled: true
  datasource:
    url: ${POSTGRESS_URL:jdbc:postgresql://postgres.default.svc.cluster.local:5432/notification}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    name: main

rabbitmq:
    host: ${rabbitmq_host:}
    port: ${rabbitmq_port:}
    username: ${rabbitmq_username:guest}
    password: ${rabbitmq_password:guest}
      
mail:
  protocol: smtps
  host: smtp.gmail.com
  username: your-mail-address@mail.com
  password: your-mail-password
  properties:
    mail.smtp:
      starttls.enable: true
      starttls.required: false
  port: 465
  test-connection: false
  properties.mail.smtp.socketFactory.port: 25

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

      group.readiness.include: '*'
      group.readiness.show-details: always

      group.liveness.include: '*'
      group.liveness.show-details: always

  endpoints:
    web:
      exposure:
        include: '*'
