server:
  port: 8082
spring:
  application.name: order
  liquibase:
    enabled: true
  datasource:
    url: ${POSTGRESS_URL:jdbc:postgresql://postgres.default.svc.cluster.local:5432/order}
    username: ${POSTGRES_USER:postgress}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    name: main
    
  rabbitmq:
    host: ${rabbitmq_host:}
    port: ${rabbitmq_port:}
    username: ${rabbitmq_username:guest}
    password: ${rabbitmq_password:guest}
    queues:
      request: orderStatusRequestQueue
      success: orderStatusSuccessQueue
      fail: orderStatusFailQueue
#this is test for jenkins
#this is test for jenkins
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

      group.readiness.include: '*'
      group.readiness.show-details: always

      group.liveness.include: '*'
      group.liveness.show-details: always

  endpoints:
    web:
      exposure:
        include: '*'
