server:
  port: 8082

spring:
  application.name: order
  liquibase:
    enabled: true
  datasource:
    url: ${POSTGRESS_URL:jdbc:tc:postgresql:10.9://postgres.e-grocery.svc.cluster.local/notification}
    username:  ${POSTGRESS_USERNAME:postgress}
    password: ${POSTGRESS_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    name: main

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

      group.readiness.include: '*'
      group.readiness.show-details: always

      group.liveness.include: '*'
      group.liveness.show-details: always

  endpoints:
    web:
      exposure:
        include: '*'
