apiVersion: v1
kind: Service
metadata:
  name: {{  .Release.Name  }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ default "TCP" .Values.service.targetport }}
      protocol: {{ .Values.service.protocol }}
      name: {{ default "http" .Values.service.name }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
