server:
  port: 8084

spring:
  application.name: ordersaga
  liquibase:
    enabled: true
  datasource:
    url: ${POSTGRESS_URL:jdbc:postgresql://postgres.default.svc.cluster.local:5432/ordersaga}
    username: ${POSTGRES_USER:postgress}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    name: main

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

      group.readiness.include: '*'
      group.readiness.show-details: always

      group.liveness.include: '*'
      group.liveness.show-details: always

  endpoints:
    web:
      exposure:
        include: '*'
