server:
  port: 8087

insert-test-images: true

spring:
  application:
    name: search
  servlet:
    multipart:
      max-file-size: 5MB

elastic:
  host: ${elastic_host:}
  port: ${elastic_port:9200}
  scheme: http
  index:
    name: product

s3:
  url: ${s3_url:http://s3.default.svc.cluster.local:4566}
  region: ${s3_region:us-east-1}
  access-key: ${s3_access_key:}
  secret-key: ${s3_secret_key:}
  buckets:
    image-bucket-name: e-grocery-img

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

      group.readiness.include: '*'
      group.readiness.show-details: always

      group.liveness.include: '*'
      group.liveness.show-details: always

  endpoints:
    web:
      exposure:
        include: '*'

  metrics:
    distribution:
      percentiles[http.server.requests]: 0.5, 0.95, 0.99, 1
      percentiles-histogram[http.server.requests]: true